NAME	= libft.a

CHK_DIR			=	0_checkers
CHK		=	$(CHK_DIR)/ft_isalnum.c \
			$(CHK_DIR)/ft_isalpha.c \
			$(CHK_DIR)/ft_isascii.c \
			$(CHK_DIR)/ft_isdigit.c \
			$(CHK_DIR)/ft_isprint.c

GNL_DIR	=	2_get_next_line
GNL		=	$(GNL_DIR)/ft_get_next_line.c\
			$(GNL_DIR)/ft_get_next_line2.c

LST_DIR	=	2_lst
LST		=	$(LST_DIR)/ft_del.c \
            $(LST_DIR)/ft_lstadd.c \
            $(LST_DIR)/ft_lstdel.c \
            $(LST_DIR)/ft_lstdelone.c \
            $(LST_DIR)/ft_lstiter.c \
            $(LST_DIR)/ft_lstmap.c \
            $(LST_DIR)/ft_lstnew.c

MEM_DIR	=	0_mem
MEM		=	$(MEM_DIR)/ft_bzero.c \
            $(MEM_DIR)/ft_memalloc.c \
            $(MEM_DIR)/ft_memccpy.c \
            $(MEM_DIR)/ft_memchr.c \
            $(MEM_DIR)/ft_memcmp.c \
            $(MEM_DIR)/ft_memcpy.c \
            $(MEM_DIR)/ft_memdel.c \
            $(MEM_DIR)/ft_memmove.c \
            $(MEM_DIR)/ft_memset.c

PUT_DIR	=	2_put
PUT		=	$(PUT_DIR)/ft_putchar.c \
            $(PUT_DIR)/ft_putchar_fd.c \
            $(PUT_DIR)/ft_putendl.c \
            $(PUT_DIR)/ft_putendl_fd.c \
            $(PUT_DIR)/ft_putnbr.c \
            $(PUT_DIR)/ft_putnbr_fd.c \
            $(PUT_DIR)/ft_putstr.c \
            $(PUT_DIR)/ft_putstr_fd.c

SCH_DIR	=	2_strchange
SCH		=	$(SCH_DIR)/ft_itoa.c \
            $(SCH_DIR)/ft_tolower.c \
            $(SCH_DIR)/ft_toupper.c

STR_DIR	=	1_string
STR		=	$(STR_DIR)/ft_strcat.c \
            $(STR_DIR)/ft_strchr.c \
            $(STR_DIR)/ft_strchrcount.c \
            $(STR_DIR)/ft_strclr.c \
            $(STR_DIR)/ft_strcmp.c \
            $(STR_DIR)/ft_strcpy.c \
            $(STR_DIR)/ft_strdel.c \
            $(STR_DIR)/ft_strdup.c \
            $(STR_DIR)/ft_strequ.c \
            $(STR_DIR)/ft_striter.c \
            $(STR_DIR)/ft_striteri.c \
            $(STR_DIR)/ft_strjoin.c \
            $(STR_DIR)/ft_strlcat.c \
            $(STR_DIR)/ft_strlcpy.c \
            $(STR_DIR)/ft_strlen.c \
            $(STR_DIR)/ft_strmap.c \
            $(STR_DIR)/ft_strmapi.c \
            $(STR_DIR)/ft_strncat.c \
            $(STR_DIR)/ft_strncmp.c \
            $(STR_DIR)/ft_strncpy.c \
            $(STR_DIR)/ft_strnequ.c \
            $(STR_DIR)/ft_strnew.c \
            $(STR_DIR)/ft_strnlen.c \
            $(STR_DIR)/ft_strnstr.c \
            $(STR_DIR)/ft_strrchr.c \
            $(STR_DIR)/ft_strsplit.c \
            $(STR_DIR)/ft_strstr.c \
            $(STR_DIR)/ft_strsub.c \
            $(STR_DIR)/ft_strtolower.c \
            $(STR_DIR)/ft_strtoupper.c \
            $(STR_DIR)/ft_strtrim.c

TONUM_DIR		=	1_tonum
TONUM	=	$(TONUM_DIR)/ft_atoli.c \
            $(TONUM_DIR)/ft_atoi.c

DSTR_DIR	=	3_dstr
DSTR	=	$(DSTR_DIR)/dstr_del.c \
			$(DSTR_DIR)/dstr_init.c \
			$(DSTR_DIR)/dstr_join.c \
			$(DSTR_DIR)/dstr_pop_back.c \
			$(DSTR_DIR)/dstr_pop_front.c \
			$(DSTR_DIR)/dstr_remove_back.c \
			$(DSTR_DIR)/dstr_remove_front.c

BIN_HEAP_DIR	=	3_binary_heap
BIN_HEAP = 	$(BIN_HEAP_DIR)/bin_free.c\
			$(BIN_HEAP_DIR)/bin_get_root.c\
			$(BIN_HEAP_DIR)/bin_heapify.c\
			$(BIN_HEAP_DIR)/bin_inc_key.c\
			$(BIN_HEAP_DIR)/bin_insert.c\
			$(BIN_HEAP_DIR)/bin_remove_root.c\
			$(BIN_HEAP_DIR)/bin_swap.c\
			$(BIN_HEAP_DIR)/binary_init.c

DARR_DIR		=	3_darr
DARR	=	$(DARR_DIR)/darr_delete.c\
			$(DARR_DIR)/darr_init.c\
			$(DARR_DIR)/darr_join.c\
			$(DARR_DIR)/darr_pop_all.c\
			$(DARR_DIR)/darr_pop_back.c\
			$(DARR_DIR)/darr_pop_front.c\
			$(DARR_DIR)/darr_remove_back.c\
			$(DARR_DIR)/darr_remove_front.c\
			$(DARR_DIR)/darr_pop_all_wo_malloc.c\
			$(DARR_DIR)/darr_pop_back_wo_malloc.c\
			$(DARR_DIR)/darr_pop_front_wo_malloc.c\
			$(DARR_DIR)/darr_shrink.c\
			$(DARR_DIR)/darr_delete_ith.c\
			$(DARR_DIR)/darr_shrink.c\
			$(DARR_DIR)/darr_timsort.c\
			$(DARR_DIR)/darr_timsort_getrun.c\
			$(DARR_DIR)/darr_timsort_merge.c\
			$(DARR_DIR)/darr_binsearch.c

PRINTF_DIR		=	3_printf
PRINTF	=	$(PRINTF_DIR)/bint_api.c \
			$(PRINTF_DIR)/c_proc.c \
			$(PRINTF_DIR)/pf_stringrunner.c \
			$(PRINTF_DIR)/di_proc.c \
			$(PRINTF_DIR)/f_proc.c \
			$(PRINTF_DIR)/f_proc_ldbl.c \
			$(PRINTF_DIR)/f_proc_powten.c \
			$(PRINTF_DIR)/f_proc_prec_ldbl.c \
			$(PRINTF_DIR)/f_proc_prec_ldbl_rounding.c \
			$(PRINTF_DIR)/f_proc_support.c \
			$(PRINTF_DIR)/f_proc_support2.c \
			$(PRINTF_DIR)/ft_printf.c \
			$(PRINTF_DIR)/handle_f_extremums.c \
			$(PRINTF_DIR)/o_proc.c \
			$(PRINTF_DIR)/o_proc_continue.c \
			$(PRINTF_DIR)/p_proc.c \
			$(PRINTF_DIR)/parsecolors.c \
			$(PRINTF_DIR)/parseman.c \
			$(PRINTF_DIR)/processor.c \
			$(PRINTF_DIR)/s_proc.c \
			$(PRINTF_DIR)/u_proc.c \
			$(PRINTF_DIR)/utils.c \
			$(PRINTF_DIR)/x_proc.c \
			$(PRINTF_DIR)/x_proc_continue.c\
			$(PRINTF_DIR)/rules_init.c


SRC			+=		$(CHK) \
					$(GNL) \
					$(LST) \
					$(MEM) \
					$(PUT) \
					$(SCH) \
					$(STR) \
					$(TONUM) \
					$(DSTR) \
					$(BIN_HEAP) \
					$(DARR) \
					$(PRINTF)

SRC_DIR			=	srcs
OBJ_DIR			=	obj

DIRS		+=		$(OBJ_DIR) \
					$(OBJ_DIR)/$(CHK_DIR) \
					$(OBJ_DIR)/$(GNL_DIR) \
					$(OBJ_DIR)/$(LST_DIR) \
					$(OBJ_DIR)/$(MEM_DIR) \
					$(OBJ_DIR)/$(PUT_DIR) \
					$(OBJ_DIR)/$(SCH_DIR) \
					$(OBJ_DIR)/$(STR_DIR) \
					$(OBJ_DIR)/$(TONUM_DIR) \
					$(OBJ_DIR)/$(DSTR_DIR) \
					$(OBJ_DIR)/$(BIN_HEAP_DIR) \
					$(OBJ_DIR)/$(DARR_DIR) \
					$(OBJ_DIR)/$(PRINTF_DIR)



SRCS			=	$(SRC:%.c=$(SRC_DIR)/%.c)
OBJ				=	$(SRC:%.c=%.o)
OBJS			=	$(SRC:%.c=$(OBJ_DIR)/%.o)
DEPS 			= 	$(OBJS:.o=.d)


.PHONY: all clean fclean re threaded

FLAGS	= -Wall -Werror -Wextra -pthread
MKDIR_P			= mkdir -p
COMPILER		= gcc
INC_DIR			= -Iincludes/

all: $(NAME)

$(NAME): $(DIRS) $(OBJS)
		ar rc $@ $(OBJS)
		ranlib $@

$(DIRS):
		$(MKDIR_P) $(DIRS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
		$(COMPILER) $(FLAGS) -MD -o $@ -c $< $(INC_DIR)

clean:
		rm -rf $(OBJ_DIR)

fclean: clean
		rm -f $(NAME)

re: fclean all

-include $(wildcard $(DEPS))
